# Generated by Django 3.2.22 on 2023-10-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_recipe', '0003_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content_method',
            field=models.TextField(default='Default content for method.'),
        ),
    ]
