# Generated by Django 3.2.22 on 2023-10-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_recipe', '0004_recipe_content_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='last_name',
        ),
    ]
